#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZGNiNDgxZTJhMTRhMmY2YTA5M2UyNzk0ZWRiYmEwZGEyMGFhODNmZjM4NGRmY2YyZTIyY2MwYTUxZmVmNWJhYmIyYzE5NjMxYWY3ZTlmZGY1OWU1NzQwODBlMGI4Zjc4YzY3MA==
  logging:
    logstash: # forward logs to ELK
      enabled: true
      host: jhipster-logstash
  metrics:
    logs: # report metrics in the logs
      enabled: true
      report-frequency: 60 # in seconds

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
